-- fizz_buzz.hs
{-
 - Players generally sit in a circle. The player designated to go first says
 - the number "1", and each player thenceforth counts one number in turn.
 - However, any number divisible by 'A' e.g. three is replaced by the word fizz
 - and any divisible by 'B' e.g. five by the word buzz. Numbers divisible by
 - both become fizz buzz. A player who hesitates or makes a mistake is either
 - eliminated.
 -
 - Write a program that prints out the the pattern generated by such a scenario
 - given the values of 'A'/'B' and 'N' which are read from an input text file.
 - The input text file contains three space delimited numbers i.e. A, B, N. The
 - program should then print out the final series of numbers using 'F' for
 - fizz, 'B' for 'buzz' and 'FB' for fizz buzz.
 -
 - Input sample:
 - Your program should read an input file (provided on the command line) which
 - contains multiple newline separated lines. Each line will contain 3 numbers
 - which are space delimited. The first number is first number to divide by
 - ('A' in this example), the second number is the second number to divide by
 - ('B' in this example) and the third number is where you should count till
 - ('N' in this example). You may assume that the input file is formatted
 - correctly and is the numbers are valid positive integers.e.g.
 -
 - 3 5 10
 - 2 7 15
 -
 - Output sample:
 -
 - Print out the series 1 through N replacing numbers divisible by 'A' by F,
 - numbers divisible by 'B' by B and numbers divisible by both as 'FB'. Since
 - the input file contains multiple sets of values, your output will print out
 - one line per set. Ensure that there are no trailing empty spaces on each
 - line you print.e.g.
 -
 - 1 2 F 4 B F 7 8 F B
 - 1 F 3 F 5 F B F 9 F 11 F 13 FB 15
 -}

import System.Environment (getArgs)

fizzBuzz n a b = map fb [1..n]
    where fb k | k `mod` a == 0 && k `mod` b == 0 = "FB"
               | k `mod` a == 0                   = "F"
               | k `mod` b == 0                   = "B"
               | otherwise                        = show k

solveProblem txt = let lns = lines txt
                       abns = [ map read $ words ln | ln <- lns ]
                       outputs = [ fizzBuzz n a b | [a,b,n] <- abns ]
                   in unlines [ unwords ln | ln <- outputs ]

main = do
    args <- getArgs
    txt <- readFile $ head args
    putStr $ solveProblem txt
